<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kamus Arisan Digital - JoyPay Platform Arisan Digital</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link href="{{ asset('css/kamus.css') }}" rel="stylesheet">
    <link href="{{ asset('css/layout.css') }}" rel="stylesheet">
</head>
<body>
    <!-- Floating Background Elements -->
    <div class="floating-elements">
        <div class="floating-item"></div>
        <div class="floating-item"></div>
        <div class="floating-item"></div>
    </div>

    <!-- Scroll Indicator -->
    <div class="scroll-indicator"></div>

    <!-- Header Section -->
    <section class="hero-section">
        <div class="container">
            <div class="hero-content">
                <h1 class="page-title">Kamus Arisan Digital</h1>
                <p class="page-subtitle">
                    Kumpulan istilah dan definisi lengkap seputar arisan digital, kloter, dan terminologi JoyPay untuk membantu pemahaman Anda
                </p>
            </div>
        </div>
    </section>

    <!-- Main Content -->
    <section class="main-content">
        <div class="container">
            <div class="content-grid">
                <!-- Main Content -->
                <div class="content-main">
                    <!-- Search Section -->
                    <div class="search-section animate-on-scroll">
                        <div class="search-container">
                            <input type="text" class="search-input" placeholder="Cari istilah arisan digital..." id="searchInput">
                            <i class="fas fa-search search-icon"></i>
                        </div>
                        <div class="search-results-count" id="resultsCount">Menampilkan semua istilah</div>
                    </div>

                    <!-- Category Filter -->
                    <div class="category-filter animate-on-scroll">
                        <button class="category-btn active" data-category="all">Semua</button>
                        <button class="category-btn" data-category="dasar">Istilah Dasar</button>
                        <button class="category-btn" data-category="teknis">Teknis</button>
                        <button class="category-btn" data-category="keuangan">Keuangan</button>
                        <button class="category-btn" data-category="teknologi">Teknologi</button>
                    </div>

                    <!-- Alphabet Filter -->
                    <div class="alphabet-filter animate-on-scroll" id="alphabetFilter">
                        <!-- Alphabet buttons will be generated by JavaScript -->
                    </div>

                    <!-- Dictionary Entries -->
                    <div class="dictionary-section animate-on-scroll">
                        <h2 class="section-title">
                            <i class="fas fa-book"></i>
                            Daftar Istilah
                        </h2>
                        
                        <div class="dictionary-grid" id="dictionaryGrid">
                            <!-- Dictionary entries will be populated by JavaScript -->
                        </div>

                        <!-- No Results -->
                        <div class="no-results" id="noResults" style="display: none;">
                            <div class="no-results-icon">
                                <i class="fas fa-search"></i>
                            </div>
                            <h3>Istilah Tidak Ditemukan</h3>
                            <p>Coba gunakan kata kunci yang berbeda atau jelajahi kategori lain</p>
                        </div>

                        <!-- Loading -->
                        <div class="loading" id="loading">
                            <div class="loading-spinner"></div>
                            <p>Memuat istilah...</p>
                        </div>
                    </div>
                </div>

                <!-- Sidebar -->
                <div class="content-sidebar">
                    <!-- Popular Terms Widget -->
                    <div class="sidebar-widget">
                        <h3 class="widget-title">
                            <i class="fas fa-list"></i>
                            Daftar Isi
                        </h3>
                        <ul class="popular-terms">
                            <li><a href="#" data-term="admin-fee">Admin Fee</a></li>
                            <li><a href="#" data-term="anggota">Anggota</a></li>
                            <li><a href="#" data-term="backup-fund">Backup Fund</a></li>
                            <li><a href="#" data-term="cashback">Cashback</a></li>
                            <li><a href="#" data-term="dashboard">Dashboard</a></li>
                            <li><a href="#" data-term="iuran">Iuran</a></li>
                            <li><a href="#" data-term="kloter">Kloter</a></li>
                            <li><a href="#" data-term="kuota">Kuota</a></li>
                            <li><a href="#" data-term="kyc">KYC</a></li>
                            <li><a href="#" data-term="nominal">Nominal</a></li>
                            <li><a href="#" data-term="notifikasi">Notifikasi</a></li>
                            <li><a href="#" data-term="pemenang">Pemenang</a></li>
                            <li><a href="#" data-term="periode">Periode</a></li>
                            <li><a href="#" data-term="referral">Referral</a></li>
                            <li><a href="#" data-term="roi">ROI</a></li>
                            <li><a href="#" data-term="slot">Slot</a></li>
                            <li><a href="#" data-term="undian">Undian</a></li>
                            <li><a href="#" data-term="verifikasi">Verifikasi</a></li>
                        </ul>
                    </div>

                    <!-- Stats Widget -->
                    <div class="stats-widget">
                        <div class="widget-title">
                            <i class="fas fa-chart-bar"></i>
                            Statistik Kamus
                        </div>
                        <div class="stats-grid">
                            <div class="stat-item">
                                <div class="stat-number" id="totalTerms">0</div>
                                <div class="stat-label">Total Istilah</div>
                            </div>
                            <div class="stat-item">
                                <div class="stat-number">4</div>
                                <div class="stat-label">Kategori</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Back to Top Button -->
    <button class="back-to-top" id="backToTop">
        <i class="fas fa-chevron-up"></i>
    </button>

    <script>
        // Dictionary data - sorted alphabetically A-Z
        const dictionaryData = [
            {
                term: "Admin Fee",
                category: "keuangan",
                pronunciation: "/ad·min fi/",
                definition: "Biaya administrasi yang dikenakan platform untuk mengelola dan memfasilitasi jalannya arisan digital.",
                example: "Admin fee untuk kloter ini sebesar 2% dari total dana yang diterima pemenang.",
                related: ["Biaya", "Platform", "Layanan"]
            },
            {
                term: "Anggota",
                category: "dasar",
                pronunciation: "/ang·go·ta/",
                definition: "Peserta yang bergabung dalam sebuah kloter arisan dan berkewajiban membayar iuran sesuai ketentuan.",
                example: "Kloter ini terdiri dari 10 anggota dengan iuran sesuai slot yang dipilih.",
                related: ["Kloter", "Peserta", "Iuran"]
            },
            {
                term: "Backup Fund",
                category: "keuangan",
                pronunciation: "/bek·ap fund/",
                definition: "Dana cadangan yang disediakan platform untuk menjamin kelancaran arisan jika ada anggota yang menunggak pembayaran.",
                example: "Backup fund memastikan pemenang undian tetap menerima dana penuh meski ada anggota yang telat bayar.",
                related: ["Jaminan", "Cadangan", "Keamanan"]
            },
            {
                term: "Dashboard",
                category: "teknologi",
                pronunciation: "/dash·board/",
                definition: "Halaman utama aplikasi yang menampilkan ringkasan informasi kloter, pembayaran, dan aktivitas arisan anggota.",
                example: "Melalui dashboard, saya bisa melihat status pembayaran dan jadwal undian semua kloter yang saya ikuti.",
                related: ["Interface", "Informasi", "Aplikasi"]
            },
            {
                term: "Iuran",
                category: "keuangan",
                pronunciation: "/i·u·ran/",
                definition: "Jumlah uang yang harus dibayarkan setiap anggota secara rutin sesuai dengan periode yang ditentukan dalam kloter.",
                example: "Iuran bulanan untuk kloter ini adalah Rp 50.000 yang dibayar setiap jadwal.",
                related: ["Pembayaran", "Nominal", "Kewajiban"]
            },
            {
                term: "Kloter",
                category: "dasar",
                pronunciation: "/klo·ter/",
                definition: "Kelompok atau grup arisan yang terdiri dari sejumlah anggota yang telah ditentukan. Setiap kloter memiliki nominal iuran, periode, dan jadwal undian yang sama.",
                example: "Saya bergabung dengan kloter arisan 12 bulan dengan nominal Rp 1.000.000 per bulan.",
                related: ["Slot", "Anggota", "Periode"]
            },
            {
                term: "Kuota",
                category: "dasar",
                pronunciation: "/ku·o·ta/",
                definition: "Batas maksimal jumlah anggota yang dapat bergabung dalam sebuah kloter arisan.",
                example: "Kuota kloter ini sudah penuh dengan 15 anggota, tidak bisa menerima pendaftar baru.",
                related: ["Slot", "Kapasitas", "Anggota"]
            },
            {
                term: "KYC",
                category: "teknis",
                pronunciation: "/kei wai si/",
                definition: "Know Your Customer, proses verifikasi identitas pelanggan untuk memenuhi regulasi dan mencegah fraud.",
                example: "Proses KYC memerlukan verifikasi ketika anda ingin masuk kloter dan melakukan pembayaran kloter.",
                related: ["Verifikasi", "Identitas", "Regulasi"]
            },
            {
                term: "Nominal",
                category: "keuangan",
                pronunciation: "/no·mi·nal/",
                definition: "Jumlah atau besaran uang yang ditetapkan untuk iuran maupun dana yang akan diterima dalam kloter arisan.",
                example: "Nominal kloter premium ini dimulai dari Rp 5.000.000 per slot.",
                related: ["Jumlah", "Iuran", "Dana"]
            },
            {
                term: "Notifikasi",
                category: "teknis",
                pronunciation: "/no·ti·fi·ka·si/",
                definition: "Pemberitahuan otomatis yang dikirim kepada anggota mengenai jadwal pembayaran, hasil undian, atau informasi penting lainnya.",
                example: "Saya menerima notifikasi bahwa pembayaran iuran akan dipotong otomatis besok.",
                related: ["Pemberitahuan", "Informasi", "Aplikasi"]
            },
            {
                term: "Pemenang",
                category: "dasar",
                pronunciation: "/pe·me·nang/",
                definition: "Anggota kloter yang terpilih melalui undian untuk menerima dana arisan pada periode tertentu.",
                example: "Pemenang undian bulan ini adalah Ibu Sari yang akan menerima dana Rp 10.000.000.",
                related: ["Undian", "Dana", "Giliran"]
            },
            {
                term: "Periode",
                category: "dasar",
                pronunciation: "/pe·ri·o·de/",
                definition: "Jangka waktu berjalannya sebuah kloter arisan, mulai dari pembentukan hingga semua anggota mendapat giliran.",
                example: "Periode kloter 12 bulan berarti arisan akan berjalan selama 12 bulan dengan 12 kali undian.",
                related: ["Durasi", "Kloter", "Jadwal"]
            },
            {
                term: "ROI",
                category: "keuangan",
                pronunciation: "/ar o ai/",
                definition: "Return on Investment, yaitu tingkat pengembalian atau keuntungan yang diperoleh dari mengikuti arisan dibandingkan dengan investasi lainnya.",
                example: "ROI dari arisan ini cukup menarik karena anggota mendapat dana lebih awal tanpa bunga.",
                related: ["Investasi", "Keuntungan", "Analisis"]
            },
            {
                term: "Slot",
                category: "dasar",
                pronunciation: "/slot/",
                definition: "Posisi atau tempat yang tersedia dalam sebuah kloter arisan. Setiap slot mewakili satu anggota dalam kloter tersebut.",
                example: "Kloter ini masih memiliki 3 slot kosong yang bisa diisi oleh anggota baru.",
                related: ["Kloter", "Anggota", "Kuota"]
            },
            {
                term: "Undian",
                category: "dasar",
                pronunciation: "/un·di·an/",
                definition: "Proses pengacakan yang dilakukan untuk menentukan anggota mana yang akan menerima dana arisan pada periode tertentu.",
                example: "Undian kloter ini dilakukan setiap tanggal 15 dan hasilnya diumumkan melalui aplikasi.",
                related: ["Pemenang", "Periode", "Transparansi"]
            },
            {
                term: "Verifikasi",
                category: "teknis",
                pronunciation: "/ve·ri·fi·ka·si/",
                definition: "Proses pemeriksaan dan validasi data anggota untuk memastikan keabsahan identitas dan rekening bank.",
                example: "Proses verifikasi membutuhkan upload bukti transfer ketika melakukan pembayaran.",
                related: ["Validasi", "Identitas", "Keamanan"]
            },
        ];

        // Generate alphabet filter
        function generateAlphabetFilter() {
            const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
            const alphabetFilter = document.getElementById('alphabetFilter');
            
            // Get available letters
            const availableLetters = new Set();
            dictionaryData.forEach(item => {
                availableLetters.add(item.term.charAt(0).toUpperCase());
            });
            
            alphabet.forEach(letter => {
                const btn = document.createElement('div');
                btn.className = `alphabet-letter ${!availableLetters.has(letter) ? 'disabled' : ''}`;
                btn.textContent = letter;
                btn.dataset.letter = letter;
                
                if (availableLetters.has(letter)) {
                    btn.addEventListener('click', () => filterByLetter(letter));
                }
                
                alphabetFilter.appendChild(btn);
            });
        }

        // Render dictionary entries
        function renderDictionary(data = dictionaryData) {
            const grid = document.getElementById('dictionaryGrid');
            const noResults = document.getElementById('noResults');
            const resultsCount = document.getElementById('resultsCount');
            
            if (data.length === 0) {
                grid.style.display = 'none';
                noResults.style.display = 'block';
                resultsCount.textContent = 'Tidak ada hasil yang ditemukan';
                return;
            }
            
            grid.style.display = 'grid';
            noResults.style.display = 'none';
            resultsCount.textContent = `Menampilkan ${data.length} istilah`;
            
            grid.innerHTML = data.map(item => `
                <div class="dictionary-entry" data-term="${item.term.toLowerCase()}" data-category="${item.category}">
                    <div class="entry-term">
                        ${item.term}
                        <span class="entry-category">${getCategoryName(item.category)}</span>
                    </div>
                    ${item.pronunciation ? `<div class="entry-pronunciation">${item.pronunciation}</div>` : ''}
                    <div class="entry-definition">${item.definition}</div>
                    ${item.example ? `
                        <div class="entry-example">
                            <div class="entry-example-title">
                                <i class="fas fa-quote-left"></i>
                                Contoh Penggunaan
                            </div>
                            <div class="entry-example-text">"${item.example}"</div>
                        </div>
                    ` : ''}
                    ${item.related && item.related.length > 0 ? `
                        <div class="entry-related">
                            <div class="entry-related-title">Istilah Terkait</div>
                            <div class="entry-related-terms">
                                ${item.related.map(term => `
                                    <a href="#" class="related-term" data-term="${term.toLowerCase()}">${term}</a>
                                `).join('')}
                            </div>
                        </div>
                    ` : ''}
                </div>
            `).join('');
            
            // Add click handlers for related terms
            document.querySelectorAll('.related-term').forEach(link => {
                link.addEventListener('click', (e) => {
                    e.preventDefault();
                    searchTerm(link.dataset.term);
                });
            });
        }

        // Get category display name
        function getCategoryName(category) {
            const categories = {
                'dasar': 'Dasar',
                'teknis': 'Teknis',
                'keuangan': 'Keuangan',
                'teknologi': 'Teknologi'
            };
            return categories[category] || category;
        }

        // Search functionality
        function searchDictionary(query) {
            if (!query.trim()) {
                renderDictionary();
                return;
            }
            
            const filtered = dictionaryData.filter(item => 
                item.term.toLowerCase().includes(query.toLowerCase()) ||
                item.definition.toLowerCase().includes(query.toLowerCase()) ||
                (item.example && item.example.toLowerCase().includes(query.toLowerCase())) ||
                (item.related && item.related.some(rel => rel.toLowerCase().includes(query.toLowerCase())))
            );
            
            renderDictionary(filtered);
        }

        // Search specific term
        function searchTerm(term) {
            const searchInput = document.getElementById('searchInput');
            searchInput.value = term;
            searchDictionary(term);
            
            // Scroll to results
            document.getElementById('dictionaryGrid').scrollIntoView({
                behavior: 'smooth',
                block: 'start'
            });
        }

        // Filter by category
        function filterByCategory(category) {
            const filtered = category === 'all' ? 
                dictionaryData : 
                dictionaryData.filter(item => item.category === category);
            
            renderDictionary(filtered);
            
            // Update active category button
            document.querySelectorAll('.category-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            document.querySelector(`[data-category="${category}"]`).classList.add('active');
        }

        // Filter by letter
        function filterByLetter(letter) {
            const filtered = dictionaryData.filter(item => 
                item.term.charAt(0).toUpperCase() === letter
            );
            
            renderDictionary(filtered);
            
            // Update active letter
            document.querySelectorAll('.alphabet-letter').forEach(btn => {
                btn.classList.remove('active');
            });
            document.querySelector(`[data-letter="${letter}"]`).classList.add('active');
            
            // Reset category filter
            document.querySelectorAll('.category-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            document.querySelector('[data-category="all"]').classList.add('active');
        }

        // Update total terms count
        function updateStats() {
            document.getElementById('totalTerms').textContent = dictionaryData.length;
        }

        // Scroll animations
        function animateOnScroll() {
            const elements = document.querySelectorAll('.animate-on-scroll');
            
            elements.forEach(element => {
                const elementTop = element.getBoundingClientRect().top;
                const elementVisible = 150;
                
                if (elementTop < window.innerHeight - elementVisible) {
                    element.classList.add('animated');
                }
            });
        }

        // Scroll indicator
        function updateScrollIndicator() {
            const winScroll = document.body.scrollTop || document.documentElement.scrollTop;
            const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
            const scrolled = (winScroll / height) * 100;
            document.querySelector('.scroll-indicator').style.width = scrolled + '%';
        }

        // Back to top functionality
        function updateBackToTop() {
            const backToTop = document.getElementById('backToTop');
            if (window.scrollY > 300) {
                backToTop.classList.add('visible');
            } else {
                backToTop.classList.remove('visible');
            }
        }

        // Initialize
        document.addEventListener('DOMContentLoaded', function() {
            generateAlphabetFilter();
            renderDictionary();
            updateStats();
            animateOnScroll();
            
            // Search input handler
            const searchInput = document.getElementById('searchInput');
            let searchTimeout;
            
            searchInput.addEventListener('input', function() {
                clearTimeout(searchTimeout);
                searchTimeout = setTimeout(() => {
                    searchDictionary(this.value);
                }, 300);
            });
            
            // Category filter handlers
            document.querySelectorAll('.category-btn').forEach(btn => {
                btn.addEventListener('click', function() {
                    filterByCategory(this.dataset.category);
                });
            });
            
            // Popular terms handlers
            document.querySelectorAll('.popular-terms a[data-term]').forEach(link => {
                link.addEventListener('click', function(e) {
                    e.preventDefault();
                    searchTerm(this.dataset.term);
                });
            });
            
            // Back to top handler
            document.getElementById('backToTop').addEventListener('click', function() {
                window.scrollTo({
                    top: 0,
                    behavior: 'smooth'
                });
            });
            
            // Scroll events
            window.addEventListener('scroll', function() {
                animateOnScroll();
                updateScrollIndicator();
                updateBackToTop();
            });
            
            // Reset filters when clicking search
            searchInput.addEventListener('focus', function() {
                document.querySelectorAll('.alphabet-letter').forEach(btn => {
                    btn.classList.remove('active');
                });
            });
        });

        // Keyboard shortcuts
        document.addEventListener('keydown', function(e) {
            // Ctrl/Cmd + K for search focus
            if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
                e.preventDefault();
                document.getElementById('searchInput').focus();
            }
            
            // Escape to clear search
            if (e.key === 'Escape') {
                const searchInput = document.getElementById('searchInput');
                searchInput.value = '';
                renderDictionary();
                searchInput.blur();
            }
        });
    </script>
</body>
</html>